spring:
  application:
    name: OpticalClinicManagementSystem
  datasource:
    url: jdbc:postgresql://localhost:5432/mmtorresoptical
    username: postgres
    password: postgres123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    show-sql: true

app:
  jwt:
    secret: BTQ9bfbqfRzRNU9Gvj+nyUDZyKoCyPxvCdvmaJvYLUnIdnE6trUb+qmSSsLfwKur
    expiration-ms: 86400000 # 24 hours

server:
  port: 8080

encryption:
  secret-key: 291b7360afa9fd8ffdd058d50a139221cee7305bd17ad6a00cfcf3e2f7e18f84